### ISSUE TITLE
No monolith or gateway apps found 

### ISSUE THREAD

**Issue by JCDavie** [ruddell/generator-jhipster-ionic#1]
I always get the same error when pointing to my jhipster project root folder.  I am using a monolyth V3.3.  I have tried with older versions, 3.2.1 and 3.2.2 projects too

**Comment by ruddell** [comment]
@JCDavie First of all, thank you for using the module.  I think the issue is my documentation...

Point to the parent folder of your JHipster project, not the project itself.  This will display a menu to choose the project (if you have several JHipster projects, you can choose only one)  I'll clarify this in my next patch.

**Comment by ruddell** [comment]
@JCDavie I was able to reproduce this on both Ubuntu and Windows.  The newest version of the module (v1.1.4) should correctly find your JHipster projects.

**Comment by JCDavie** [comment]
@ruddell works perfectly now :)
